#!/bin/bash
#Handbrake batch script to recursively encode every file in a certain directory
FILES=./*
for f in $FILES
do
  #f is the input file names, this line replaces all avi's (input) with mkv's (output)
  g=${f/${f##*.}/mkv}
  

  echo "Processing ${f} file..."

  # Edit this line with the various parameters you want to use. See https://trac.handbrake.fr/wiki/CLIGuide
#  HandBrakeCLI -C 2 -i "${f}" -o "${g}" -e x264 -S 40 -2 -T -E AC3 -B 64 -5 -8 strong
  if [ "${f##*.}" != "mkv" ]
  then
    HandBrakeCLI --native-language eng --subtitle scan,1 --subtitle-forced 1 --quality 25 --maxWidth 720 --format mkv --input "${f}" --encoder x264 --aencoder copy --audio-copy-mask dtshd,dts,ac3,mp3 --audio-fallback lame --output "${g}"
  fi
  echo "Done with ${f}!"
done
