#!/bin/bash
#avconv batch script to recursively strip audio from every file in a certain directory
FILES=./*
for f in $FILES
do
  #f is the input file names, this line replaces all avi's (input) with mkv's (output)
  g=${f/${f##*.}/mp3}
  

  echo "Processing ${f} file..."

  if [ "${f##*.}" != "mp3" ]
  then
    avconv -i "${f}" "${g}"
  fi
  echo "Done with ${f}!"
done
