#!/bin/bash
#Handbrake batch script to recursively encode every file in a certain directory
FILES=./*
for f in $FILES
do
  #f is the input file names, this line replaces all avi's (input) with mkv's (output)
  g=${f/${f##*.}/mkv}
  

  echo "Processing ${f} file..."

  if [ "${f##*.}" == "mkv" ]
  then
    g=${g}.mkv
  fi
  # Edit this line with the various parameters you want to use. See https://trac.handbrake.fr/wiki/CLIGuide
  HandBrakeCLI --native-language eng --subtitle scan,1 --subtitle-forced 1 --quality 23 --maxWidth 720 --format mkv --input "${f}" --encoder x264 --aencoder copy --audio-copy-mask dtshd,dts,ac3 --audio-fallback lame --output "${g}" --detelecine --grayscale
  echo "Done with ${f}!"
done
