#!/bin/bash
vlc v4l2:///dev/video1 --v4l2-standard=NTSC --input-slave=alsa://hw:3,0 --v4l2-dev=/dev/video1 --v4l2-input=1 --v4l2-audio-input=1 --v4l2-width=640 --v4l2-height=480 --v4l2-aspect-ratio=4:3
